name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: 'contains(github.event.head_commit.message, ''docs:'')'

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Run Install package
        run: pnpm install

      - name: Run core build
        run: pnpm run core-dev

      - name: Run docs Build
        run: pnpm run docs-build

      - name: Run echo cname
        run: echo 'pick.elonehoo.xyz' > docs/.vitepress/dist/CNAME

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: docs/.vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
